component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/poi/.*
- ./bin/org/apache/poi/common/.*
- ./bin/org/apache/poi/common/usermodel/.*
- ./bin/org/apache/poi/contrib/.*
- ./bin/org/apache/poi/contrib/metrics/.*
- ./bin/org/apache/poi/contrib/poibrowser/.*
- ./bin/org/apache/poi/ddf/.*
- ./bin/org/apache/poi/dev/.*
- ./bin/org/apache/poi/extractor/.*
- ./bin/org/apache/poi/hdf/.*
- ./bin/org/apache/poi/hdf/event/.*
- ./bin/org/apache/poi/hdf/extractor/.*
- ./bin/org/apache/poi/hdf/extractor/data/.*
- ./bin/org/apache/poi/hdf/extractor/util/.*
- ./bin/org/apache/poi/hdf/model/.*
- ./bin/org/apache/poi/hdf/model/hdftypes/.*
- ./bin/org/apache/poi/hdf/model/hdftypes/definitions/.*
- ./bin/org/apache/poi/hdf/model/util/.*
- ./bin/org/apache/poi/hdgf/.*
- ./bin/org/apache/poi/hdgf/chunks/.*
- ./bin/org/apache/poi/hdgf/dev/.*
- ./bin/org/apache/poi/hdgf/exceptions/.*
- ./bin/org/apache/poi/hdgf/extractor/.*
- ./bin/org/apache/poi/hdgf/pointers/.*
- ./bin/org/apache/poi/hdgf/streams/.*
- ./bin/org/apache/poi/hpbf/.*
- ./bin/org/apache/poi/hpbf/dev/.*
- ./bin/org/apache/poi/hpbf/extractor/.*
- ./bin/org/apache/poi/hpbf/model/.*
- ./bin/org/apache/poi/hpbf/model/qcbits/.*
- ./bin/org/apache/poi/hpsf/.*
- ./bin/org/apache/poi/hpsf/basic/.*
- ./bin/org/apache/poi/hpsf/examples/.*
- ./bin/org/apache/poi/hpsf/extractor/.*
- ./bin/org/apache/poi/hpsf/wellknown/.*
- ./bin/org/apache/poi/hslf/.*
- ./bin/org/apache/poi/hslf/blip/.*
- ./bin/org/apache/poi/hslf/dev/.*
- ./bin/org/apache/poi/hslf/examples/.*
- ./bin/org/apache/poi/hslf/exceptions/.*
- ./bin/org/apache/poi/hslf/extractor/.*
- ./bin/org/apache/poi/hslf/model/.*
- ./bin/org/apache/poi/hslf/model/textproperties/.*
- ./bin/org/apache/poi/hslf/record/.*
- ./bin/org/apache/poi/hslf/usermodel/.*
- ./bin/org/apache/poi/hslf/util/.*
- ./bin/org/apache/poi/hsmf/.*
- ./bin/org/apache/poi/hsmf/datatypes/.*
- ./bin/org/apache/poi/hsmf/examples/.*
- ./bin/org/apache/poi/hsmf/exceptions/.*
- ./bin/org/apache/poi/hsmf/model/.*
- ./bin/org/apache/poi/hsmf/parsers/.*
- ./bin/org/apache/poi/hssf/.*
- ./bin/org/apache/poi/hssf/contrib/.*
- ./bin/org/apache/poi/hssf/contrib/view/.*
- ./bin/org/apache/poi/hssf/dev/.*
- ./bin/org/apache/poi/hssf/eventmodel/.*
- ./bin/org/apache/poi/hssf/eventusermodel/.*
- ./bin/org/apache/poi/hssf/eventusermodel/dummyrecord/.*
- ./bin/org/apache/poi/hssf/eventusermodel/examples/.*
- ./bin/org/apache/poi/hssf/extractor/.*
- ./bin/org/apache/poi/hssf/model/.*
- ./bin/org/apache/poi/hssf/record/.*
- ./bin/org/apache/poi/hssf/record/aggregates/.*
- ./bin/org/apache/poi/hssf/record/cf/.*
- ./bin/org/apache/poi/hssf/record/chart/.*
- ./bin/org/apache/poi/hssf/record/common/.*
- ./bin/org/apache/poi/hssf/record/constant/.*
- ./bin/org/apache/poi/hssf/record/cont/.*
- ./bin/org/apache/poi/hssf/record/crypto/.*
- ./bin/org/apache/poi/hssf/record/formula/.*
- ./bin/org/apache/poi/hssf/record/formula/atp/.*
- ./bin/org/apache/poi/hssf/record/formula/eval/.*
- ./bin/org/apache/poi/hssf/record/formula/function/.*
- ./bin/org/apache/poi/hssf/record/formula/functions/.*
- ./bin/org/apache/poi/hssf/record/formula/udf/.*
- ./bin/org/apache/poi/hssf/record/pivot/.*
- ./bin/org/apache/poi/hssf/record/pivottable/.*
- ./bin/org/apache/poi/hssf/usermodel/.*
- ./bin/org/apache/poi/hssf/usermodel/contrib/.*
- ./bin/org/apache/poi/hssf/usermodel/examples/.*
- ./bin/org/apache/poi/hssf/util/.*
- ./bin/org/apache/poi/hwpf/.*
- ./bin/org/apache/poi/hwpf/dev/.*
- ./bin/org/apache/poi/hwpf/extractor/.*
- ./bin/org/apache/poi/hwpf/model/.*
- ./bin/org/apache/poi/hwpf/model/io/.*
- ./bin/org/apache/poi/hwpf/model/types/.*
- ./bin/org/apache/poi/hwpf/sprm/.*
- ./bin/org/apache/poi/hwpf/usermodel/.*
- ./bin/org/apache/poi/openxml4j/.*
- ./bin/org/apache/poi/openxml4j/exceptions/.*
- ./bin/org/apache/poi/openxml4j/opc/.*
- ./bin/org/apache/poi/openxml4j/opc/compliance/.*
- ./bin/org/apache/poi/openxml4j/opc/internal/.*
- ./bin/org/apache/poi/openxml4j/opc/internal/marshallers/.*
- ./bin/org/apache/poi/openxml4j/opc/internal/signature/.*
- ./bin/org/apache/poi/openxml4j/opc/internal/unmarshallers/.*
- ./bin/org/apache/poi/openxml4j/opc/signature/.*
- ./bin/org/apache/poi/openxml4j/util/.*
- ./bin/org/apache/poi/poifs/.*
- ./bin/org/apache/poi/poifs/common/.*
- ./bin/org/apache/poi/poifs/dev/.*
- ./bin/org/apache/poi/poifs/eventfilesystem/.*
- ./bin/org/apache/poi/poifs/filesystem/.*
- ./bin/org/apache/poi/poifs/property/.*
- ./bin/org/apache/poi/poifs/storage/.*
- ./bin/org/apache/poi/sl/.*
- ./bin/org/apache/poi/sl/usermodel/.*
- ./bin/org/apache/poi/ss/.*
- ./bin/org/apache/poi/ss/examples/.*
- ./bin/org/apache/poi/ss/extractor/.*
- ./bin/org/apache/poi/ss/formula/.*
- ./bin/org/apache/poi/ss/formula/eval/.*
- ./bin/org/apache/poi/ss/formula/eval/forked/.*
- ./bin/org/apache/poi/ss/usermodel/.*
- ./bin/org/apache/poi/ss/usermodel/contrib/.*
- ./bin/org/apache/poi/ss/util/.*
- ./bin/org/apache/poi/util/.*
- ./bin/org/apache/poi/util/data/.*
- ./bin/org/apache/poi/xslf/.*
- ./bin/org/apache/poi/xslf/extractor/.*
- ./bin/org/apache/poi/xslf/usermodel/.*
- ./bin/org/apache/poi/xssf/.*
- ./bin/org/apache/poi/xssf/dev/.*
- ./bin/org/apache/poi/xssf/eventusermodel/.*
- ./bin/org/apache/poi/xssf/eventusermodel/examples/.*
- ./bin/org/apache/poi/xssf/extractor/.*
- ./bin/org/apache/poi/xssf/io/.*
- ./bin/org/apache/poi/xssf/model/.*
- ./bin/org/apache/poi/xssf/usermodel/.*
- ./bin/org/apache/poi/xssf/usermodel/examples/.*
- ./bin/org/apache/poi/xssf/usermodel/extensions/.*
- ./bin/org/apache/poi/xssf/usermodel/helpers/.*
- ./bin/org/apache/poi/xssf/util/.*
- ./bin/org/apache/poi/xwpf/.*
- ./bin/org/apache/poi/xwpf/extractor/.*
- ./bin/org/apache/poi/xwpf/model/.*
- ./bin/org/apache/poi/xwpf/usermodel/.*
- ./docs/.*
- ./docs/apidocs/.*
- ./docs/apidocs/org/.*
- ./docs/apidocs/org/apache/.*
- ./docs/apidocs/org/apache/poi/.*
- ./docs/apidocs/org/apache/poi/class-use/.*
- ./docs/apidocs/org/apache/poi/common/.*
- ./docs/apidocs/org/apache/poi/common/usermodel/.*
- ./docs/apidocs/org/apache/poi/common/usermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/contrib/.*
- ./docs/apidocs/org/apache/poi/contrib/metrics/.*
- ./docs/apidocs/org/apache/poi/contrib/metrics/class-use/.*
- ./docs/apidocs/org/apache/poi/contrib/poibrowser/.*
- ./docs/apidocs/org/apache/poi/contrib/poibrowser/class-use/.*
- ./docs/apidocs/org/apache/poi/ddf/.*
- ./docs/apidocs/org/apache/poi/ddf/class-use/.*
- ./docs/apidocs/org/apache/poi/dev/.*
- ./docs/apidocs/org/apache/poi/dev/class-use/.*
- ./docs/apidocs/org/apache/poi/extractor/.*
- ./docs/apidocs/org/apache/poi/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/hdgf/.*
- ./docs/apidocs/org/apache/poi/hdgf/chunks/.*
- ./docs/apidocs/org/apache/poi/hdgf/chunks/class-use/.*
- ./docs/apidocs/org/apache/poi/hdgf/class-use/.*
- ./docs/apidocs/org/apache/poi/hdgf/dev/.*
- ./docs/apidocs/org/apache/poi/hdgf/dev/class-use/.*
- ./docs/apidocs/org/apache/poi/hdgf/exceptions/.*
- ./docs/apidocs/org/apache/poi/hdgf/exceptions/class-use/.*
- ./docs/apidocs/org/apache/poi/hdgf/extractor/.*
- ./docs/apidocs/org/apache/poi/hdgf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/hdgf/pointers/.*
- ./docs/apidocs/org/apache/poi/hdgf/pointers/class-use/.*
- ./docs/apidocs/org/apache/poi/hdgf/streams/.*
- ./docs/apidocs/org/apache/poi/hdgf/streams/class-use/.*
- ./docs/apidocs/org/apache/poi/hpbf/.*
- ./docs/apidocs/org/apache/poi/hpbf/class-use/.*
- ./docs/apidocs/org/apache/poi/hpbf/dev/.*
- ./docs/apidocs/org/apache/poi/hpbf/dev/class-use/.*
- ./docs/apidocs/org/apache/poi/hpbf/extractor/.*
- ./docs/apidocs/org/apache/poi/hpbf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/hpbf/model/.*
- ./docs/apidocs/org/apache/poi/hpbf/model/class-use/.*
- ./docs/apidocs/org/apache/poi/hpbf/model/qcbits/.*
- ./docs/apidocs/org/apache/poi/hpbf/model/qcbits/class-use/.*
- ./docs/apidocs/org/apache/poi/hpsf/.*
- ./docs/apidocs/org/apache/poi/hpsf/class-use/.*
- ./docs/apidocs/org/apache/poi/hpsf/extractor/.*
- ./docs/apidocs/org/apache/poi/hpsf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/hpsf/wellknown/.*
- ./docs/apidocs/org/apache/poi/hpsf/wellknown/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/.*
- ./docs/apidocs/org/apache/poi/hslf/blip/.*
- ./docs/apidocs/org/apache/poi/hslf/blip/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/dev/.*
- ./docs/apidocs/org/apache/poi/hslf/dev/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/exceptions/.*
- ./docs/apidocs/org/apache/poi/hslf/exceptions/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/extractor/.*
- ./docs/apidocs/org/apache/poi/hslf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/model/.*
- ./docs/apidocs/org/apache/poi/hslf/model/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/model/textproperties/.*
- ./docs/apidocs/org/apache/poi/hslf/model/textproperties/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/record/.*
- ./docs/apidocs/org/apache/poi/hslf/record/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/usermodel/.*
- ./docs/apidocs/org/apache/poi/hslf/usermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/hslf/util/.*
- ./docs/apidocs/org/apache/poi/hslf/util/class-use/.*
- ./docs/apidocs/org/apache/poi/hsmf/.*
- ./docs/apidocs/org/apache/poi/hsmf/class-use/.*
- ./docs/apidocs/org/apache/poi/hsmf/datatypes/.*
- ./docs/apidocs/org/apache/poi/hsmf/datatypes/class-use/.*
- ./docs/apidocs/org/apache/poi/hsmf/exceptions/.*
- ./docs/apidocs/org/apache/poi/hsmf/exceptions/class-use/.*
- ./docs/apidocs/org/apache/poi/hsmf/parsers/.*
- ./docs/apidocs/org/apache/poi/hsmf/parsers/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/.*
- ./docs/apidocs/org/apache/poi/hssf/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/contrib/.*
- ./docs/apidocs/org/apache/poi/hssf/contrib/view/.*
- ./docs/apidocs/org/apache/poi/hssf/contrib/view/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/dev/.*
- ./docs/apidocs/org/apache/poi/hssf/dev/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/eventmodel/.*
- ./docs/apidocs/org/apache/poi/hssf/eventmodel/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/eventusermodel/.*
- ./docs/apidocs/org/apache/poi/hssf/eventusermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/eventusermodel/dummyrecord/.*
- ./docs/apidocs/org/apache/poi/hssf/eventusermodel/dummyrecord/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/extractor/.*
- ./docs/apidocs/org/apache/poi/hssf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/model/.*
- ./docs/apidocs/org/apache/poi/hssf/model/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/.*
- ./docs/apidocs/org/apache/poi/hssf/record/aggregates/.*
- ./docs/apidocs/org/apache/poi/hssf/record/aggregates/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/cf/.*
- ./docs/apidocs/org/apache/poi/hssf/record/cf/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/chart/.*
- ./docs/apidocs/org/apache/poi/hssf/record/chart/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/common/.*
- ./docs/apidocs/org/apache/poi/hssf/record/common/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/constant/.*
- ./docs/apidocs/org/apache/poi/hssf/record/constant/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/cont/.*
- ./docs/apidocs/org/apache/poi/hssf/record/cont/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/crypto/.*
- ./docs/apidocs/org/apache/poi/hssf/record/crypto/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/atp/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/atp/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/eval/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/eval/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/function/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/function/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/functions/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/functions/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/udf/.*
- ./docs/apidocs/org/apache/poi/hssf/record/formula/udf/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/record/pivottable/.*
- ./docs/apidocs/org/apache/poi/hssf/record/pivottable/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/usermodel/.*
- ./docs/apidocs/org/apache/poi/hssf/usermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/usermodel/contrib/.*
- ./docs/apidocs/org/apache/poi/hssf/usermodel/contrib/class-use/.*
- ./docs/apidocs/org/apache/poi/hssf/util/.*
- ./docs/apidocs/org/apache/poi/hssf/util/class-use/.*
- ./docs/apidocs/org/apache/poi/hwpf/.*
- ./docs/apidocs/org/apache/poi/hwpf/class-use/.*
- ./docs/apidocs/org/apache/poi/hwpf/dev/.*
- ./docs/apidocs/org/apache/poi/hwpf/dev/class-use/.*
- ./docs/apidocs/org/apache/poi/hwpf/extractor/.*
- ./docs/apidocs/org/apache/poi/hwpf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/hwpf/model/.*
- ./docs/apidocs/org/apache/poi/hwpf/model/class-use/.*
- ./docs/apidocs/org/apache/poi/hwpf/model/io/.*
- ./docs/apidocs/org/apache/poi/hwpf/model/io/class-use/.*
- ./docs/apidocs/org/apache/poi/hwpf/model/types/.*
- ./docs/apidocs/org/apache/poi/hwpf/model/types/class-use/.*
- ./docs/apidocs/org/apache/poi/hwpf/sprm/.*
- ./docs/apidocs/org/apache/poi/hwpf/sprm/class-use/.*
- ./docs/apidocs/org/apache/poi/hwpf/usermodel/.*
- ./docs/apidocs/org/apache/poi/hwpf/usermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/openxml4j/.*
- ./docs/apidocs/org/apache/poi/openxml4j/exceptions/.*
- ./docs/apidocs/org/apache/poi/openxml4j/exceptions/class-use/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/class-use/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/internal/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/internal/class-use/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/internal/marshallers/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/internal/marshallers/class-use/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/internal/signature/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/internal/signature/class-use/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/internal/unmarshallers/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/internal/unmarshallers/class-use/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/signature/.*
- ./docs/apidocs/org/apache/poi/openxml4j/opc/signature/class-use/.*
- ./docs/apidocs/org/apache/poi/openxml4j/util/.*
- ./docs/apidocs/org/apache/poi/openxml4j/util/class-use/.*
- ./docs/apidocs/org/apache/poi/poifs/.*
- ./docs/apidocs/org/apache/poi/poifs/common/.*
- ./docs/apidocs/org/apache/poi/poifs/common/class-use/.*
- ./docs/apidocs/org/apache/poi/poifs/dev/.*
- ./docs/apidocs/org/apache/poi/poifs/dev/class-use/.*
- ./docs/apidocs/org/apache/poi/poifs/eventfilesystem/.*
- ./docs/apidocs/org/apache/poi/poifs/eventfilesystem/class-use/.*
- ./docs/apidocs/org/apache/poi/poifs/filesystem/.*
- ./docs/apidocs/org/apache/poi/poifs/filesystem/class-use/.*
- ./docs/apidocs/org/apache/poi/poifs/property/.*
- ./docs/apidocs/org/apache/poi/poifs/property/class-use/.*
- ./docs/apidocs/org/apache/poi/poifs/storage/.*
- ./docs/apidocs/org/apache/poi/poifs/storage/class-use/.*
- ./docs/apidocs/org/apache/poi/sl/.*
- ./docs/apidocs/org/apache/poi/sl/usermodel/.*
- ./docs/apidocs/org/apache/poi/sl/usermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/ss/.*
- ./docs/apidocs/org/apache/poi/ss/class-use/.*
- ./docs/apidocs/org/apache/poi/ss/extractor/.*
- ./docs/apidocs/org/apache/poi/ss/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/ss/formula/.*
- ./docs/apidocs/org/apache/poi/ss/formula/class-use/.*
- ./docs/apidocs/org/apache/poi/ss/formula/eval/.*
- ./docs/apidocs/org/apache/poi/ss/formula/eval/class-use/.*
- ./docs/apidocs/org/apache/poi/ss/formula/eval/forked/.*
- ./docs/apidocs/org/apache/poi/ss/formula/eval/forked/class-use/.*
- ./docs/apidocs/org/apache/poi/ss/usermodel/.*
- ./docs/apidocs/org/apache/poi/ss/usermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/ss/usermodel/contrib/.*
- ./docs/apidocs/org/apache/poi/ss/usermodel/contrib/class-use/.*
- ./docs/apidocs/org/apache/poi/ss/util/.*
- ./docs/apidocs/org/apache/poi/ss/util/class-use/.*
- ./docs/apidocs/org/apache/poi/util/.*
- ./docs/apidocs/org/apache/poi/util/class-use/.*
- ./docs/apidocs/org/apache/poi/xslf/.*
- ./docs/apidocs/org/apache/poi/xslf/class-use/.*
- ./docs/apidocs/org/apache/poi/xslf/extractor/.*
- ./docs/apidocs/org/apache/poi/xslf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/xslf/usermodel/.*
- ./docs/apidocs/org/apache/poi/xslf/usermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/xssf/.*
- ./docs/apidocs/org/apache/poi/xssf/dev/.*
- ./docs/apidocs/org/apache/poi/xssf/dev/class-use/.*
- ./docs/apidocs/org/apache/poi/xssf/eventusermodel/.*
- ./docs/apidocs/org/apache/poi/xssf/eventusermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/xssf/extractor/.*
- ./docs/apidocs/org/apache/poi/xssf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/xssf/model/.*
- ./docs/apidocs/org/apache/poi/xssf/model/class-use/.*
- ./docs/apidocs/org/apache/poi/xssf/usermodel/.*
- ./docs/apidocs/org/apache/poi/xssf/usermodel/class-use/.*
- ./docs/apidocs/org/apache/poi/xssf/usermodel/extensions/.*
- ./docs/apidocs/org/apache/poi/xssf/usermodel/extensions/class-use/.*
- ./docs/apidocs/org/apache/poi/xssf/usermodel/helpers/.*
- ./docs/apidocs/org/apache/poi/xssf/usermodel/helpers/class-use/.*
- ./docs/apidocs/org/apache/poi/xssf/util/.*
- ./docs/apidocs/org/apache/poi/xssf/util/class-use/.*
- ./docs/apidocs/org/apache/poi/xwpf/.*
- ./docs/apidocs/org/apache/poi/xwpf/extractor/.*
- ./docs/apidocs/org/apache/poi/xwpf/extractor/class-use/.*
- ./docs/apidocs/org/apache/poi/xwpf/model/.*
- ./docs/apidocs/org/apache/poi/xwpf/model/class-use/.*
- ./docs/apidocs/org/apache/poi/xwpf/usermodel/.*
- ./docs/apidocs/org/apache/poi/xwpf/usermodel/class-use/.*
- ./docs/hdgf/.*
- ./docs/hpbf/.*
- ./docs/hpsf/.*
- ./docs/hsmf/.*
- ./docs/hwpf/.*
- ./docs/images/.*
- ./docs/oxml4j/.*
- ./docs/poifs/.*
- ./docs/skin/.*
- ./docs/skin/images/.*
- ./docs/slideshow/.*
- ./docs/spreadsheet/.*
- ./legal/.*
- ./lib/.*
- ./test-data/.*
- ./test-data/ddf/.*
- ./test-data/diagram/.*
- ./test-data/document/.*
- ./test-data/hpsf/.*
- ./test-data/hsmf/.*
- ./test-data/openxml4j/.*
- ./test-data/poifs/.*
- ./test-data/publisher/.*
- ./test-data/slideshow/.*
- ./test-data/spreadsheet/.*
